name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build iTextSharp.LGPLv2.Core lib
      run: dotnet build ./src/iTextSharp.LGPLv2.Core/iTextSharp.LGPLv2.Core.csproj --configuration Release

    - name: Run iTextSharp.LGPLv2.Core lib functional tests
      run: dotnet test ./src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextSharp.LGPLv2.Core.FunctionalTests.csproj
      
    - name: Push Package to NuGet.org
      if: github.event_name == 'push'
      run: dotnet nuget push **\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
